//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp_OTOGALERİ
{
    using System;
    using System.Collections.Generic;
    
    public partial class giris
    {
        public int ID { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string kullanıcı_adı { get; set; }
        public string sifre { get; set; }
        public string sifre_tekrar { get; set; }
    }
}
