//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp_OTOGALERİ
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class oto_galeriEntities : DbContext
    {
        public oto_galeriEntities()
            : base("name=oto_galeriEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Araç> Araç { get; set; }
        public virtual DbSet<giris> giris { get; set; }
        public virtual DbSet<Müsteri> Müsteri { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<Satis> Satis { get; set; }
        public virtual DbSet<Sube> Sube { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
